src/CPy.Web/Areas/Admin/Controllers/SysFunctionController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using CPy.Dto.Admin;
using CPy.Dto.Base;
using CPy.IApplication.Admin;
using CPy.ModelBinder;
using CPy.ResultDto.ExcuteResult;
using CPy.Web.Controllers;

namespace CPy.Web.Areas.Admin.Controllers
{
    public class SysFunctionController:BaseController
    {
        private readonly ISysFunctionApplication _sysFunctionApplication;

        public SysFunctionController(ISysFunctionApplication sysFunctionApplication)
        {
            _sysFunctionApplication = sysFunctionApplication;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail()
        {
            return View();
        }

        [HttpPost]
        public JsonResult InitDataGrid([ModelBinder(typeof(BaseModelBinder<SysFunctionSearchParam>))] SysFunctionSearchParam param)
        {
            var result = HandleWebResult.HandleResult(_sysFunctionApplication.InitDataGrid(param));
            return HandleWebResult.HandleResult(_sysFunctionApplication.InitDataGrid(param));
        }

        public JsonResult InitDetail(Guid id)
        {
            return HandleWebResult.HandleResult(_sysFunctionApplication.InitDetail(id));
        }

        [HttpPost]
        public JsonResult Add([ModelBinder(typeof(BaseModelBinder<SysFunctionAddParam>))]SysFunctionAddParam param)
        {
            return HandleWebResult.HandleResult(_sysFunctionApplication.Add(param));
        }

        public JsonResult DeleteFunction([ModelBinder(typeof(BaseModelBinder<BaseDeleteDto>))]BaseDeleteDto dto )
        {
            return HandleWebResult.HandleResult(_sysFunctionApplication.Delete(dto.Ids));
        }
    }
}

src/CPy.Web/Areas/Admin/Controllers/SysModuleController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using CPy.Dto.Admin;
using CPy.Dto.Base;
using CPy.IApplication.Admin;
using CPy.Log;
using CPy.ModelBinder;
using CPy.ResultDto.ExcuteResult;
using CPy.Web.Controllers;
using WebGrease.Css.Extensions;

namespace CPy.Web.Areas.Admin.Controllers
{
    public class SysModuleController : BaseController
    {
        private readonly ISysModuleApplication _sysModuleApplication;

        public SysModuleController(ISysModuleApplication sysModuleApplication)
        {
            _sysModuleApplication = sysModuleApplication;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SysModuleDetail()
        {
            return View();
        }

        [HttpPost]
        public JsonResult InitGrid([ModelBinder(typeof(BaseModelBinder<SysModuleSearchParam>))]SysModuleSearchParam param)
        {
            LogHelper.Info("datefafafajfajfioajf");
            LogHelper.Error("this is error");
            var result = _sysModuleApplication.Search(param);
            var a = HandleWebResult.HandleResult(result);
            return a;
        }

        [HttpPost]
        public JsonResult InitDetail(Guid id)
        {
            return HandleWebResult.HandleResult(_sysModuleApplication.GetSysModuleById(id));
        }

        [HttpPost]
        public JsonResult Save(SysModuleSaveParam param)
        {
            return HandleWebResult.HandleResult(_sysModuleApplication.Save(param));
        }

        [HttpPost]
        public JsonResult Delete([ModelBinder(typeof(BaseModelBinder<BaseDeleteDto>))]BaseDeleteDto dto)
        {
            return HandleWebResult.HandleResult(_sysModuleApplication.Delete(dto.Ids));
        }

        [HttpGet]
        public JsonResult GetModuleList()
        {
            var dic = _sysModuleApplication.GetModuleList();

            return HandleWebResult.HandleDictionary(dic);
        }
    }
}

src/CPy.Web/Areas/Layout/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CPy.IApplication.Admin;
using CPy.ResultDto.ExcuteResult;

namespace CPy.Web.Areas.Layout.Controllers
{
    public class LayoutController : Controller
    {
        private readonly ILayoutApplication _layoutApplication;

        public LayoutController(ILayoutApplication layoutApplication)
        {
            _layoutApplication = layoutApplication;
        }

        // GET: Layout/Layout
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetModuleList()
        {
            return HandleWebResult.HandleResult(_layoutApplication.GetModuleList());
        }
    }
}

src/CPy.Web/Controllers/BaseController.cs
using System.Web.Mvc;

namespace CPy.Web.Controllers
{
    public class BaseController:Controller
    {
         
    }
}

src/CPy.Web/Areas/Admin/Views/SysFunction/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="padding: 10px 60px 20px 60px">
    @Html.Partial("_FormToolBarPartialPage")

    <form id="ff" class="formbody" method="post">

        <input type="hidden" name="Id" />
        <table cellpadding="5">
            <tr>
                <td>模块:</td>
                <td>
                    <input id="moduleCmb" class="easyui-combobox" validtype="comboxValidate['moduleCmb','请选择模块']" name="SysModuleId" style="width: 200px; height: 25px;" data-options="required:true,valueField:'Id',textField:'MName'">
                </td>
            </tr>
            <tr>
                <td>编号:</td>
                <td><input class="easyui-textbox" style="height: 25px; width: 200px;" type="text" name="FNo" data-options="required:true" /></td>
            </tr>
            <tr>
                <td>名称:</td>
                <td><input class="easyui-textbox" style="height: 25px; width: 200px;" type="text" name="FName" data-options="required:true" /></td>
            </tr>
            <tr>
                <td>URL:</td>
                <td><input class="easyui-textbox" style="height: 25px; width: 200px;" type="text" name="FUrl" data-options="required:true"/></td>
            </tr>
            <tr>
                <td id="ht">添加Html</td>
                <td id="ht1"></td>
            </tr>
        </table>
    </form>


</div>

<script>

    $(function () {
        var id = HandleUrl.GetQueryString("Id");
        var moduleId = HandleUrl.GetQueryString("ModuleId");

        //初始化模块下拉控件
        HandleForm.InitCombobox('moduleCmb', '@Url.Action("GetModuleList","SysModule",new{area="Admin"})', function (data) {
            $("#hdModuleId").val(data.Id);
        });

        //id不为空，则为编辑加载form表单
        if (id) {
            HandleForm.LoadForm('ff', '@Url.Action("InitDetail", "SysFunction", new { area = "Admin"})?id=' + id);
            //$('#moduleCmb').combobox('setValue', moduleId);
        } else {
            setdefaulevalue();
        }
        $("#ht").click(function () {
            console.log('add');
            addHtml();
        });
    });

    function setdefaulevalue() {
        var moduleId = HandleUrl.GetQueryString("ModuleId");
        if (moduleId) {
            $('#moduleCmb').combobox('setValue', moduleId);
        } else {
            $('#moduleCmb').combobox('setValue', "00000000-0000-0000-0000-000000000000");
        }
    }

    function submitForm() {
        HandleForm.SubmitForm('ff', '@Url.Action("Add","SysFunction",new{area="Admin"})', '@Url.Action("Index","SysFunction",new{area="Admin"})');
    }

    function clearForm() {
        $("#ff").form('clear');
    }

    function back() {
        location.href = '@Url.Action("Index","SysFunction",new{area="Admin"})';
    }

    function addHtml() {
        var html = "<ul>";
        html += "<li>121212121212</li>";
        html += "<li>qwqwqwqwqww</li>";
        html += "<li>adadadadadsa</li>";
        html += "</ul>";
        $(html).appendTo("#ht1");
    }
</script>

src/CPy.Web/Areas/Admin/Views/SysFunction/Index.cshtml
@using CPy.Common.ToolStrip
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    var moduleId;
    $(function () {
        HandleDateGrid.InitLeftDataGird("modules_dg", "module_toolbar", "/Admin/SysModule/InitGrid", "Id", true, function (rowIndex, rowData) {
            moduleId = rowData.Id;
            HandleDateGrid.LoadDataGrid("functions_dg", {
                ModuleId: moduleId
            });
        });
        HandleDateGrid.InitDataGrid("functions_dg", "function_toolbar", "/Admin/SysFunction/InitDataGrid", "Id", false);

    });
    function formatOper(val, row, index) {
        var id = row.Id;
        return '<a href="/Admin/SysFunction/Detail?Id=' + id + '&ModuleId=' + row.SysModuleId + '">修改</a>';
    }


    function add() {
        if (moduleId) {
            location.href = "/Admin/SysFunction/Detail?ModuleId=" + moduleId;
        } else {
            location.href = "/Admin/SysFunction/Detail";
        }
    }
    function deleteItem() {
        console.log('remove');
        HandleDateGrid.DeleteDataGrid('functions_dg', '/Admin/SysFunction/DeleteFunction');
    }
    //菜单查询
    function function_toolbarsearch() {
        var param = {
            FunctionName: $("#FName").val(),
            ModuleId: moduleId
        };
        HandleDateGrid.LoadDataGrid("functions_dg", param);
    }
    //菜单重置
    function function_toolbarreset() {
        $("#FName").textbox('setValue', '');
        var param = {
            FunctionName: "",
            ModuleId: ""
        };
        HandleDateGrid.LoadDataGrid("functions_dg", param);
    }
    //模块查询
    function module_toolbarsearch() {
        var param = {
            MName: $("#MName").val()
        };
        HandleDateGrid.LoadDataGrid("modules_dg", param);
    }
</script>
<div data-options="region:'west',split:true,title:'导航菜单'" style="width: 300px;">
    @Html.Partial("_ToolBarPartialPage", new ToolBar()
    {
        ToolBarId = "module_toolbar",
        SearchModules = new List<SearchModule>()
        {
            new SearchModule(){ControlType = SearchControlType.Text,Id = "MName",Title = "模块"}
        }
    })
    <table id="modules_dg" title="模块" class="easyui-datagrid">
        <thead>
            <tr>
                <th data-options="field:'MNo',width:100">编号</th>
                <th data-options="field:'MName',width:100">名称</th>
            </tr>
        </thead>
    </table>
</div>
<div data-options="region:'center'">
    @Html.Partial("_ToolBarPartialPage", new ToolBar()
    {
        ToolBarId = "function_toolbar",
        IsEnableReset = true,
        SearchModules = new List<SearchModule>()
        {
            new SearchModule(){ControlType = SearchControlType.Text,Id = "FName",Title = "菜单名"}
        },
        FunctionModules = new List<FunctionModule>()
        {
            new FunctionModule(){IsEnable = true,Id="Add"},
            new FunctionModule(){IsEnable = true,Id="Remove"}
        }
    })
    <table id="functions_dg" title="菜单" class="easyui-datagrid">
        <thead>
            <tr>
                <th data-options="field:'FNo',width:100">编号</th>
                <th data-options="field:'FName',width:100">名称</th>
                <th data-options="field:'FUrl',width:100">路径</th>
                <th data-options="field:'_operate',width:80,align:'center',formatter:formatOper">操作</th>
            </tr>
        </thead>
    </table>
</div>

src/CPy.Web/Areas/Admin/Views/SysModule/Index.cshtml
@using CPy.Common.ToolStrip
<script>
    $(function () {
        HandleDateGrid.InitDataGrid("dg", 'toolbar', "@Url.Action("InitGrid", "SysModule")", "Id", false,
            function(rowIndex, rowData) {
            },
            function(rowIndex, rowData) {
                location.href = '/Admin/SysModule/SysModuleDetail?Id=' + rowData.Id;
            });
        //$("#toolbarsearchbtn").bind('click', search);
    });
    function formatOper(val, row, index) {
        var id = row.Id;
        return '<a href="/Admin/SysModule/SysModuleDetail?Id='+id+'">修改</a>';
    }

    function add() {
        location.href = '/Admin/SysModule/SysModuleDetail';
    }

    function deleteItem() {
        console.log('remove');
        HandleDateGrid.DeleteDataGrid('dg', '/Admin/SysModule/Delete');
    }

    function reset() {
        HandleDateGrid.LoadDataGrid('dg', {
            KeyWord: ""
        });
    }

    function toolbarsearch() {
        var keyword = $('#MName').textbox('getValue');
        console.log(keyword);
        HandleDateGrid.LoadDataGrid('dg', {
            MName: keyword
        });
    }
</script>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_ToolBarPartialPage",new ToolBar()
{
    ToolBarId = "toolbar",
    FunctionModules = new List<FunctionModule>()
    {
        new FunctionModule(){Id = "Add",IsEnable = true},
        new FunctionModule(){Id = "Remove",IsEnable = true}
    },
    SearchModules = new List<SearchModule>()
    {
        new SearchModule(){Title = "名称",Id ="MName",ControlType = SearchControlType.Text},
    }
})

<table id="dg" title="My Users" class="easyui-datagrid">
    <thead>
        <tr>
            <th data-options="field:'MNo',width:100">编号</th>
            <th data-options="field:'MName',width:100">名称</th>
            <th data-options="field:'Description',width:100">说明</th>
            <th data-options="field:'_operate',width:80,align:'center',formatter:formatOper">操作</th>
        </tr>
    </thead>

</table>

src/CPy.Web/Areas/Admin/Views/SysModule/SysModuleDetail.cshtml
@{
    ViewBag.Title = "模块详情";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    $(function () {
        var id = HandleUrl.GetQueryString("Id");
        if (id) {
            HandleDate.LoadForm('ff', '/Admin/SysModule/InitDetail?Id=' + id);
        }
    });

    function clearForm() {
        $("#ff").form('clear');
    }

    function back() {
        location.href = '/Admin/SysModule/Index';
    }

    function submitForm() {
        HandleDate.SubmitForm('ff', '/Admin/SysModule/Save', function() {
            location.href = '/Admin/SysModule/Index';
        });
    }
</script>

<div style="padding: 10px 60px 20px 60px">
    <div style="border-bottom: 1px solid #95B8E7; margin-bottom: 20px;padding-bottom: 5px">
        <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-save" plain="true" onclick=" submitForm() ">提交</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-clear" plain="true" onclick=" clearForm() ">清除</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-back" plain="true" onclick=" back() ">返回</a>
    </div>
    <form id="ff" method="post">

        <input type="hidden" name="Id"/>
        <table cellpadding="5">
            <tr>
                <td>编号:</td>
                <td><input class="easyui-textbox" style="height: 30px; width: 200px;" type="text" name="MNo" data-options="required:true"/></td>
            </tr>
            <tr>
                <td>名称:</td>
                <td><input class="easyui-textbox" style="height: 30px; width: 200px;" type="text" name="MName" data-options="required:true"/></td>
            </tr>
            <tr>
                <td>描述:</td>
                <td><input class="easyui-textbox" style="height: 60px; width: 300px;" name="Description" data-options="multiline:true"/></td>
            </tr>

        </table>
    </form>
</div>

src/CPy.Web/Areas/Layout/Views/Layout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>TonyKit 后台管理系统</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/easyui/css")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Content/Scripts/jqueryui.layout.common.js" type="text/javascript"></script>
    @*<link rel="stylesheet/less" type="text/css" href="~/Content/less/main.layout.common.less" />
        <script src="~/Content/Scripts/less.min.js"></script>*@
</head>
<body class="easyui-layout">
    <div data-options="region:'north',border:false" style="height: 70px; background: #2596ea; padding: 10px">
        <p style="width: 300px; height: 50px; line-height: 50px; color: #fff; margin: 0; float: left; font-size: 25px">TonyKit 后台管理系统</p>
    </div>
    <div data-options="region:'west',split:true,title:'导航菜单'" style="width: 170px;">
        <div class="easyui-accordion" data-options="fit:true,border:false">
            <div title="系统管理" data-options="iconCls:'own-icon own-icon-sys'">
                    <ul>
                        <li>
                                <div>
                                    <a href="javascript:void(0)" class="layout-menu" src="@Url.Action("Index", "SysModule", new {area = "Admin"})"><span class="own-icon own-icon-nav ">&nbsp;</span>模块管理</a>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <a href="javascript:void(0)" class="layout-menu" src="@Url.Action("Index", "SysFunction", new {area = "Admin"})"><span class="own-icon own-icon-nav ">&nbsp;</span>菜单管理</a>
                                </div>
                            </li>
                    </ul>
                </div>
                @*<div title="系统管理" data-options="iconCls:'own-icon own-icon-sys'">
                    <ul>
                        <li>
                            <div>
                                <a href="javascript:void(0)" class="layout-menu" iconcls="icon-nav" src="@Url.Action("Index", "SysModule", new {area = "Admin"})">模块管理</a>
                            </div>
                        </li>
                        <li>
                            <div>
                                <a href="javascript:void(0)" class="layout-menu" src="@Url.Action("Index", "User", new {area = "User"})">用户管理</a>
                            </div>
                        </li>
                    </ul>
                </div>*@
        </div>
    </div>
    <div data-options="region:'south',border:false" style="height: 40px; padding: 10px;">south region</div>

    <div data-options="region:'center'">
        <div id="tabs" class="easyui-tabs" style="height: 100%">
            <div title="主页" style="padding: 20px; display: none; border: 0">
                this is MainPage
            </div>
        </div>
    </div>
    <div id="mm" class="easyui-menu cs-tab-menu">
        <div id="refresh">刷新</div>
        <div class="menu-sep"></div>
        <div id="close">关闭</div>
        <div id="closeother">关闭其他</div>
        <div id="closeall">关闭全部</div>
    </div>
    @*<script>
        var resultdata = [
            {
                MNo: "",
                MName: "",
                SysFunctions: [
                    {
                        FNo: "",
                        FName: "",
                        FUrl: ""
                    }
                ]
            }
        ];

        $(function () {
            HandleData.LoadData('@Url.Action("GetModuleList","Layout")', function (data) {
                resultdata = data.ResultData;
                $.each(resultdata, function (index, moduleValue) {
                    var title = "<span class=\"panel-icon own-icon own-icon-sys\"></span><span style=\"margin-left:20px\">" + moduleValue.MName + "</span>";
                    var content = "<ul>";
                    $.each(moduleValue.SysFunctions, function (index, funcValue) {
                        content += "<li>";
                        content += "<div>";
                        content += "<a href=\"javascript:void(0)\" class=\"layout-menu\" iconcls=\"icon-nav\" src=\"" + funcValue.FUrl + "\"><span class=\"own-icon own-icon-nav \">&nbsp;</span>" + funcValue.FName+ "</a>";
                        content += "</div>";
                        content += "</li>";
                    });
                    content += "</ul>";
                    console.log(title);
                    console.log(content);
                    $(".easyui-accordion").accordion('add', {
                        title: title,
                        content: content,
                        selected: false
                    });
                });

            });
            //$(".easyui-accordion li a").click(function () {
            //    console.log('addtab');
            //    var $this = $(this);
            //    var href = $this.attr('src');
            //    var title = $this.text();
            //    addTab($this, title, href);
            //});
            $(".easyui-accordion li a").each(function(index,value) {
                var $this = $(this);
                console.log($this.text());
                $this.onClick(function() {
                    var href = $this.attr('src');
                    var title = $this.text();
                    addTab($this, title, href);
                });
            });
            tabCloseEven();
        });

    </script>*@
</body>
</html>

src/CPy.Web/Views/Shared/_FormToolBarPartialPage.cshtml
<div class="formtoolbar">
    <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-save" plain="true" onclick=" submitForm() ">提交</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-clear" plain="true" onclick=" clearForm() ">清除</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-back" plain="true" onclick=" back() ">返回</a>
</div>

src/CPy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/easyui/css")
    @Scripts.Render("~/bundles/jquery")
    <style>
        .formtoolbar {
            position: fixed;
            top: 0;
            width: 90%;
            z-index: 999;
            padding: 5px 10px;
            border-bottom: 1px solid #95B8E7;
            background-color: #fff;
            -ms-opacity: 7;
            opacity: 7;
        }

        .formbody {
            margin-top: 40px;
        }
    </style>
    <script>
        $(function () {
            $.extend($.fn.validatebox.defaults.rules, {
                minLength: {
                    validator: function (value, param) {
                        return value.length >= param[0];
                    },
                    message: 'Please enter at least {0} characters.'
                }
            });
            $.extend($.fn.validatebox.defaults.rules, {
                 comboxValidate: {
                      validator: function(value, comboboxId,message) {
                          if ($('#' + comboboxId).combobox('getText') == '请选择') {
                                return false;
                          }
                           return true;
                      },
                      message: "{1}"
                 }
            });
            $.extend($.fn.validatebox.defaults.rules, {
                required: {
                    validator: function (value, param) {
                        if (param.length==0) {
                            return false;
                        }
                        return true;
                    },
                    message: "{1}"
                }
            });
        });
    </script>
</head>
<body class="easyui-layout" style="overflow: auto">
    @RenderBody()
</body>
</html>

src/CPy.Web/Views/Shared/_ToolBarPartialPage.cshtml
@using CPy.Common.ToolStrip
@model CPy.Common.ToolStrip.ToolBar

<div id="@Model.ToolBarId">
    <div style="margin-left: 10px">

        @if (Model.FunctionModules != null)
        {
            foreach (var functionModule in Model.FunctionModules)
            {
                if (functionModule.Id == "Add" && functionModule.IsEnable)
                {
                    <a class="easyui-linkbutton" iconcls="icon-add" plain="true" onclick="add() ">添加</a>
                }
                if (functionModule.Id == "Remove" && functionModule.IsEnable)
                {
                    <a class="easyui-linkbutton" iconcls="icon-remove" plain="true" onclick="deleteItem()">删除</a>
                }
            }
        }


        @if (Model.FunctionModules != null && Model.SearchModules != null)
        {
            <div style="display: inline-block; border-left: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(255, 255, 255); margin: 0 2px 0 2px; height: 22px; vertical-align: middle;"></div>
        }


        @if (Model.SearchModules != null)
        {

            foreach (var searchModule in Model.SearchModules)
            {
                if (searchModule.ControlType == SearchControlType.DateBox)
                {
                    <span style="vertical-align: middle; margin: 0 2px 0 2px">
                        日期从：<input class="easyui-datebox" id="StartDate" style="width: 120px" data-options="formatter:dateformat">
                        到：<input class="easyui-datebox" id="EndDate" style="width: 120px" data-options="formatter:dateformat">
                    </span>
                }
                else if (searchModule.ControlType == SearchControlType.ComboBox)
                {
                    <span style="vertical-align: middle; margin: 0 2px 0 2px">
                        @searchModule.Title：<input class="easyui-combobox" id="@searchModule.Id"
                                                   data-options="valueField:'id',textField:'text',url:'get_data.php'">
                    </span>
                }
                else if (searchModule.ControlType == SearchControlType.Text)
                {
                    <span style="vertical-align: middle; margin: 0 2px 0 2px">
                        @searchModule.Title：<input class="easyui-textbox" id="@searchModule.Id" style="width: 120px">
                    </span>
                }
            }
            <a class="easyui-linkbutton" iconcls="icon-search" plain="true" onclick=@(@Model.ToolBarId + "search()")>查询</a>
            if (@Model.IsEnableReset)
            {
                <a class="easyui-linkbutton" iconcls="icon-reload" plain="true" onclick=@(@Model.ToolBarId + "reset()")>重置</a>
            }
        }


    </div>
</div>

<script>
    function dateformat(date) {
        var y = date.getFullYear();
        var m = date.getMonth() + 1;
        var d = date.getDate();
        return y + '-' + m + '-' + d;
    }
</script>